const kPricesResponseMap = {
  "result": {
    "PSSA3:BZ": {
      "securityType": "Common Stock",
      "symbol": "PSSA3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "pssa3:bz",
      "tickerName": "PSSA3:BZ",
      "template": "Stock",
      "tinyName": "Porto Seguro SA",
      "name": "Porto Seguro SA",
      "watchlist": true,
      "resourceId": "PSSA3:BZ",
      "last": "48.09",
      "netChange": "0.56",
      "lastPriceTime": 1619640420,
      "pctChange1M": "2.23",
      "yearHigh": "59.93",
      "dayHigh": "48.52",
      "volume": 661000.0,
      "yearLow": "39.47",
      "dayLow": "47.30",
      "pctChangeYTD": "-1.86",
      "lastPriceAllSessions": "48.09",
      "lastPriceTimeAllSessions": 1619640420,
      "pctChange": "1.18"
    },
    "XPML11:BZ": {
      "securityType": "Closed-End Fund",
      "symbol": "XPML11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ClosedEnd",
      "region": "AMERICAS",
      "ticker": "xpml11:bz",
      "tickerName": "XPML11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "XP MALLS FDO INV IMOB FII",
      "name": "XP MALLS FDO INV IMOB FII",
      "watchlist": true,
      "resourceId": "XPML11:BZ",
      "last": "103.42",
      "netChange": "-1.23",
      "lastPriceTime": 1619640360,
      "yearHigh": "120.00",
      "dayHigh": "105.60",
      "volume": 34244.0,
      "yearLow": "82.00",
      "dayLow": "103.42",
      "pctChange": "-1.18"
    }
  }
};
