const kPricesResponseMap = {
  "result": {
    "ABEV3:BZ": {
      "securityType": "Common Stock",
      "symbol": "ABEV3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "abev3:bz",
      "tickerName": "ABEV3:BZ",
      "template": "Stock",
      "tinyName": "Ambev SA",
      "name": "Ambev SA",
      "watchlist": true,
      "resourceId": "ABEV3:BZ",
      "last": "17.29",
      "netChange": "-0.18",
      "lastPriceTime": 1622132506,
      "pctChange1M": "13.08",
      "yearHigh": "17.80",
      "dayHigh": "17.44",
      "volume": 9000000.0,
      "yearLow": "12.04",
      "dayLow": "17.22",
      "pctChangeYTD": "10.54",
      "lastPriceAllSessions": "17.29",
      "lastPriceTimeAllSessions": 1622132506,
      "pctChange": "-1.03"
    },
    "B3SA3:BZ": {
      "securityType": "Common Stock",
      "symbol": "B3SA3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "b3sa3:bz",
      "tickerName": "B3SA3:BZ",
      "template": "Stock",
      "tinyName": "B3 SA - Brasil Bolsa Balcao",
      "name": "B3 SA - Brasil Bolsa Balcao",
      "watchlist": true,
      "resourceId": "B3SA3:BZ",
      "last": "16.84",
      "netChange": "-0.26",
      "lastPriceTime": 1622132506,
      "pctChange1M": "-4.59",
      "yearHigh": "23.00",
      "dayHigh": "17.18",
      "volume": 2.16446E+7,
      "yearLow": "14.71",
      "dayLow": "16.79",
      "pctChangeYTD": "-17.58",
      "lastPriceAllSessions": "16.84",
      "lastPriceTimeAllSessions": 1622132506,
      "pctChange": "-1.52"
    },
    "BCFF11:BZ": {
      "securityType": "Closed-End Fund",
      "symbol": "BCFF11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ClosedEnd",
      "region": "AMERICAS",
      "ticker": "bcff11:bz",
      "tickerName": "BCFF11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "FII BTG Pactual Fundo de Fundos",
      "name": "FII BTG Pactual Fundo de Fundos",
      "watchlist": true,
      "resourceId": "BCFF11:BZ",
      "last": "85.51",
      "netChange": "0.36",
      "lastPriceTime": 1622132502,
      "yearHigh": "95.12",
      "dayHigh": "85.60",
      "volume": 33718.0,
      "yearLow": "81.35",
      "dayLow": "84.49",
      "pctChange": "0.42"
    },
    "EGIE3:BZ": {
      "securityType": "Common Stock",
      "symbol": "EGIE3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "egie3:bz",
      "tickerName": "EGIE3:BZ",
      "template": "Stock",
      "tinyName": "Engie Brasil Energia SA",
      "name": "Engie Brasil Energia SA",
      "watchlist": true,
      "resourceId": "EGIE3:BZ",
      "last": "40.48",
      "netChange": "-0.06",
      "lastPriceTime": 1622132482,
      "pctChange1M": "-1.84",
      "yearHigh": "47.70",
      "dayHigh": "40.96",
      "volume": 578000.0,
      "yearLow": "38.31",
      "dayLow": "40.41",
      "pctChangeYTD": "-7.87",
      "lastPriceAllSessions": "40.48",
      "lastPriceTimeAllSessions": 1622132482,
      "pctChange": "-0.15"
    },
    "ENBR3:BZ": {
      "securityType": "Common Stock",
      "symbol": "ENBR3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "enbr3:bz",
      "tickerName": "ENBR3:BZ",
      "template": "Stock",
      "tinyName": "EDP - Energias do Brasil SA",
      "name": "EDP - Energias do Brasil SA",
      "watchlist": true,
      "resourceId": "ENBR3:BZ",
      "last": "18.83",
      "netChange": "-0.15",
      "lastPriceTime": 1622132510,
      "pctChange1M": "1.35",
      "yearHigh": "20.65",
      "dayHigh": "19.11",
      "volume": 795500.0,
      "yearLow": "16.93",
      "dayLow": "18.83",
      "pctChangeYTD": "-4.17",
      "lastPriceAllSessions": "18.83",
      "lastPriceTimeAllSessions": 1622132510,
      "pctChange": "-0.79"
    },
    "FLRY3:BZ": {
      "securityType": "Common Stock",
      "symbol": "FLRY3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "flry3:bz",
      "tickerName": "FLRY3:BZ",
      "template": "Stock",
      "tinyName": "Fleury SA",
      "name": "Fleury SA",
      "watchlist": true,
      "resourceId": "FLRY3:BZ",
      "last": "26.30",
      "netChange": "-0.40",
      "lastPriceTime": 1622132496,
      "pctChange1M": "3.50",
      "yearHigh": "29.81",
      "dayHigh": "26.76",
      "volume": 694100.0,
      "yearLow": "22.55",
      "dayLow": "26.28",
      "pctChangeYTD": "-2.66",
      "lastPriceAllSessions": "26.30",
      "lastPriceTimeAllSessions": 1622132496,
      "pctChange": "-1.50"
    },
    "GNDI3:BZ": {
      "securityType": "Common Stock",
      "symbol": "GNDI3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "gndi3:bz",
      "tickerName": "GNDI3:BZ",
      "template": "Stock",
      "tinyName": "Notre Dame Intermedica Participacoes SA",
      "name": "Notre Dame Intermedica Participacoes SA",
      "watchlist": true,
      "resourceId": "GNDI3:BZ",
      "last": "86.07",
      "netChange": "-1.02",
      "lastPriceTime": 1622132476,
      "pctChange1M": "5.75",
      "yearHigh": "103.04",
      "dayHigh": "87.09",
      "volume": 1338500.0,
      "yearLow": "60.00",
      "dayLow": "85.09",
      "pctChangeYTD": "9.87",
      "lastPriceAllSessions": "86.07",
      "lastPriceTimeAllSessions": 1622132476,
      "pctChange": "-1.17"
    },
    "HGRU11:BZ": {
      "securityType": "Closed-End Fund",
      "symbol": "HGRU11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ClosedEnd",
      "region": "AMERICAS",
      "ticker": "hgru11:bz",
      "tickerName": "HGRU11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "CSHG Renda Urbana FII",
      "name": "CSHG Renda Urbana FII",
      "watchlist": true,
      "resourceId": "HGRU11:BZ",
      "last": "117.80",
      "netChange": "1.80",
      "lastPriceTime": 1622132474,
      "yearHigh": "131.89",
      "dayHigh": "117.95",
      "volume": 22243.0,
      "yearLow": "108.73",
      "dayLow": "115.96",
      "pctChange": "1.55"
    },
    "HYPE3:BZ": {
      "securityType": "Common Stock",
      "symbol": "HYPE3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "hype3:bz",
      "tickerName": "HYPE3:BZ",
      "template": "Stock",
      "tinyName": "Hypera SA",
      "name": "Hypera SA",
      "watchlist": true,
      "resourceId": "HYPE3:BZ",
      "last": "35.39",
      "netChange": "0.24",
      "lastPriceTime": 1622132483,
      "pctChange1M": "2.14",
      "yearHigh": "37.15",
      "dayHigh": "35.67",
      "volume": 1097900.0,
      "yearLow": "27.03",
      "dayLow": "35.14",
      "pctChangeYTD": "3.33",
      "lastPriceAllSessions": "35.39",
      "lastPriceTimeAllSessions": 1622132483,
      "pctChange": "0.68"
    },
    "ITUB3:BZ": {
      "securityType": "Common Stock",
      "symbol": "ITUB3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "itub3:bz",
      "tickerName": "ITUB3:BZ",
      "template": "Stock",
      "tinyName": "Itau Unibanco Holding SA",
      "name": "Itau Unibanco Holding SA",
      "watchlist": true,
      "resourceId": "ITUB3:BZ",
      "last": "25.94",
      "netChange": "-0.39",
      "lastPriceTime": 1622132476,
      "pctChange1M": "7.19",
      "yearHigh": "29.26",
      "dayHigh": "26.50",
      "volume": 228600.0,
      "yearLow": "21.02",
      "dayLow": "25.92",
      "pctChangeYTD": "-6.75",
      "lastPriceAllSessions": "25.94",
      "lastPriceTimeAllSessions": 1622132476,
      "pctChange": "-1.48"
    },
    "LREN3:BZ": {
      "securityType": "Common Stock",
      "symbol": "LREN3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "lren3:bz",
      "tickerName": "LREN3:BZ",
      "template": "Stock",
      "tinyName": "Lojas Renner SA",
      "name": "Lojas Renner SA",
      "watchlist": true,
      "resourceId": "LREN3:BZ",
      "last": "46.62",
      "netChange": "0.62",
      "lastPriceTime": 1622132499,
      "pctChange1M": "15.40",
      "yearHigh": "49.90",
      "dayHigh": "47.39",
      "volume": 5495200.0,
      "yearLow": "35.73",
      "dayLow": "45.79",
      "pctChangeYTD": "7.07",
      "lastPriceAllSessions": "46.62",
      "lastPriceTimeAllSessions": 1622132499,
      "pctChange": "1.35"
    },
    "MDIA3:BZ": {
      "securityType": "Common Stock",
      "symbol": "MDIA3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "mdia3:bz",
      "tickerName": "MDIA3:BZ",
      "template": "Stock",
      "tinyName": "M Dias Branco SA",
      "name": "M Dias Branco SA",
      "watchlist": true,
      "resourceId": "MDIA3:BZ",
      "last": "27.45",
      "netChange": "-0.04",
      "lastPriceTime": 1622132462,
      "pctChange1M": "-1.37",
      "yearHigh": "41.82",
      "dayHigh": "27.67",
      "volume": 462400.0,
      "yearLow": "25.35",
      "dayLow": "27.28",
      "pctChangeYTD": "-19.41",
      "lastPriceAllSessions": "27.45",
      "lastPriceTimeAllSessions": 1622132462,
      "pctChange": "-0.15"
    },
    "MGLU3:BZ": {
      "securityType": "Common Stock",
      "symbol": "MGLU3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "mglu3:bz",
      "tickerName": "MGLU3:BZ",
      "template": "Stock",
      "tinyName": "Magazine Luiza SA",
      "name": "Magazine Luiza SA",
      "watchlist": true,
      "resourceId": "MGLU3:BZ",
      "last": "19.61",
      "netChange": "-0.06",
      "lastPriceTime": 1622131761,
      "pctChange1M": "-6.40",
      "yearHigh": "28.31",
      "dayHigh": "19.84",
      "volume": 6517600.0,
      "yearLow": "14.63",
      "dayLow": "19.47",
      "pctChangeYTD": "-21.40",
      "lastPriceAllSessions": "19.61",
      "lastPriceTimeAllSessions": 1622131761,
      "pctChange": "-0.31"
    },
    "NTCO3:BZ": {
      "securityType": "Common Stock",
      "symbol": "NTCO3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "ntco3:bz",
      "tickerName": "NTCO3:BZ",
      "template": "Stock",
      "tinyName": "Natura & Co Holding SA",
      "name": "Natura & Co Holding SA",
      "watchlist": true,
      "resourceId": "NTCO3:BZ",
      "last": "51.93",
      "netChange": "0.68",
      "lastPriceTime": 1622132490,
      "pctChange1M": "9.51",
      "yearHigh": "54.60",
      "dayHigh": "52.12",
      "volume": 2109600.0,
      "yearLow": "36.10",
      "dayLow": "51.20",
      "pctChangeYTD": "-1.09",
      "lastPriceAllSessions": "51.93",
      "lastPriceTimeAllSessions": 1622132490,
      "pctChange": "1.33"
    },
    "PSSA3:BZ": {
      "securityType": "Common Stock",
      "symbol": "PSSA3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "pssa3:bz",
      "tickerName": "PSSA3:BZ",
      "template": "Stock",
      "tinyName": "Porto Seguro SA",
      "name": "Porto Seguro SA",
      "watchlist": true,
      "resourceId": "PSSA3:BZ",
      "last": "51.37",
      "netChange": "-0.02",
      "lastPriceTime": 1622132478,
      "pctChange1M": "8.08",
      "yearHigh": "59.93",
      "dayHigh": "51.82",
      "volume": 294700.0,
      "yearLow": "41.66",
      "dayLow": "51.15",
      "pctChangeYTD": "5.20",
      "lastPriceAllSessions": "51.37",
      "lastPriceTimeAllSessions": 1622132478,
      "pctChange": "-0.04"
    },
    "TOTS3:BZ": {
      "securityType": "Common Stock",
      "symbol": "TOTS3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "tots3:bz",
      "tickerName": "TOTS3:BZ",
      "template": "Stock",
      "tinyName": "TOTVS SA",
      "name": "TOTVS SA",
      "watchlist": true,
      "resourceId": "TOTS3:BZ",
      "last": "33.19",
      "netChange": "0.25",
      "lastPriceTime": 1622132505,
      "pctChange1M": "8.22",
      "yearHigh": "34.94",
      "dayHigh": "33.44",
      "volume": 911700.0,
      "yearLow": "19.25",
      "dayLow": "32.61",
      "pctChangeYTD": "15.56",
      "lastPriceAllSessions": "33.19",
      "lastPriceTimeAllSessions": 1622132505,
      "pctChange": "0.76"
    },
    "WEGE3:BZ": {
      "securityType": "Common Stock",
      "symbol": "WEGE3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "wege3:bz",
      "tickerName": "WEGE3:BZ",
      "template": "Stock",
      "tinyName": "WEG SA",
      "name": "WEG SA",
      "watchlist": true,
      "resourceId": "WEGE3:BZ",
      "last": "32.93",
      "netChange": "0.13",
      "lastPriceTime": 1622132513,
      "pctChange1M": "-11.02",
      "yearHigh": "46.93",
      "dayHigh": "33.22",
      "volume": 3448800.0,
      "yearLow": "19.80",
      "dayLow": "32.65",
      "pctChangeYTD": "-13.04",
      "lastPriceAllSessions": "32.93",
      "lastPriceTimeAllSessions": 1622132513,
      "pctChange": "0.40"
    },
    "WIZS3:BZ": {
      "securityType": "Common Stock",
      "symbol": "WIZS3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "wizs3:bz",
      "tickerName": "WIZS3:BZ",
      "template": "Stock",
      "tinyName": "Wiz Solucoes e Corretagem de Seguros SA",
      "name": "Wiz Solucoes e Corretagem de Seguros SA",
      "watchlist": true,
      "resourceId": "WIZS3:BZ",
      "last": "11.56",
      "netChange": "0.16",
      "lastPriceTime": 1622132500,
      "pctChange1M": "13.44",
      "yearHigh": "13.29",
      "dayHigh": "12.12",
      "volume": 3331700.0,
      "yearLow": "5.85",
      "dayLow": "11.32",
      "pctChangeYTD": "43.78",
      "lastPriceAllSessions": "11.56",
      "lastPriceTimeAllSessions": 1622132500,
      "pctChange": "1.40"
    },
    "XPLG11:BZ": {
      "securityType": "Closed-End Fund",
      "symbol": "XPLG11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ClosedEnd",
      "region": "AMERICAS",
      "ticker": "xplg11:bz",
      "tickerName": "XPLG11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "XP Log FII",
      "name": "XP Log FII",
      "watchlist": true,
      "resourceId": "XPLG11:BZ",
      "last": "112.82",
      "netChange": "0.78",
      "lastPriceTime": 1622132490,
      "yearHigh": "135.41",
      "dayHigh": "113.19",
      "volume": 39466.0,
      "yearLow": "112.00",
      "dayLow": "112.07",
      "pctChange": "0.70"
    },
    "XPML11:BZ": {
      "securityType": "Closed-End Fund",
      "symbol": "XPML11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ClosedEnd",
      "region": "AMERICAS",
      "ticker": "xpml11:bz",
      "tickerName": "XPML11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "XP MALLS FDO INV IMOB FII",
      "name": "XP MALLS FDO INV IMOB FII",
      "watchlist": true,
      "resourceId": "XPML11:BZ",
      "last": "102.63",
      "netChange": "0.05",
      "lastPriceTime": 1622132510,
      "yearHigh": "120.00",
      "dayHigh": "102.99",
      "volume": 23593.0,
      "yearLow": "93.51",
      "dayLow": "102.11",
      "pctChange": "0.05"
    }
  }
};
