const kPricesResponseMap = {
  "result": {
    "PSSA3:BZ": {
      "securityType": "Common Stock",
      "symbol": "PSSA3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "pssa3:bz",
      "tickerName": "PSSA3:BZ",
      "template": "Stock",
      "tinyName": "Porto Seguro SA",
      "name": "Porto Seguro SA",
      "watchlist": true,
      "resourceId": "PSSA3:BZ",
      "last": "50.0",
      "netChange": "0.56",
      "lastPriceTime": 1619640420,
      "pctChange1M": "2.23",
      "yearHigh": "59.93",
      "dayHigh": "48.52",
      "volume": 661000.0,
      "yearLow": "39.47",
      "dayLow": "47.30",
      "pctChangeYTD": "-1.86",
      "lastPriceAllSessions": "48.09",
      "lastPriceTimeAllSessions": 1619640420,
      "pctChange": "1.18"
    },
    "ITUB3:BZ": {
      "securityType": "Common Stock",
      "symbol": "ITUB3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "itub3:bz",
      "tickerName": "ITUB3:BZ",
      "template": "Stock",
      "tinyName": "Itau Unibanco Holding SA",
      "name": "Itau Unibanco Holding SA",
      "watchlist": true,
      "resourceId": "ITUB3:BZ",
      "last": "25.57",
      "netChange": "0.39",
      "lastPriceTime": 1621023011,
      "pctChange1M": "3.65",
      "yearHigh": "29.26",
      "dayHigh": "25.75",
      "volume": 663000.0,
      "yearLow": "20.44",
      "dayLow": "25.14",
      "pctChangeYTD": "-8.08",
      "pctChange": "1.55"
    },
    "XPML11:BZ": {
      "securityType": "Closed-End Fund",
      "symbol": "XPML11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ClosedEnd",
      "region": "AMERICAS",
      "ticker": "xpml11:bz",
      "tickerName": "XPML11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "XP MALLS FDO INV IMOB FII",
      "name": "XP MALLS FDO INV IMOB FII",
      "watchlist": true,
      "resourceId": "XPML11:BZ",
      "last": "100.0",
      "netChange": "-1.23",
      "lastPriceTime": 1619640360,
      "yearHigh": "120.00",
      "dayHigh": "105.60",
      "volume": 34244.0,
      "yearLow": "82.00",
      "dayLow": "103.42",
      "pctChange": "-1.18"
    },
    "HGLG11:BZ": {
      "securityType": "Closed-End Fund",
      "symbol": "HGLG11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ClosedEnd",
      "region": "AMERICAS",
      "ticker": "hglg11:bz",
      "tickerName": "HGLG11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "CSHG Logistica FI Imobiliario",
      "name": "CSHG Logistica FI Imobiliario",
      "watchlist": true,
      "resourceId": "HGLG11:BZ",
      "last": "171.23",
      "netChange": "-0.48",
      "lastPriceTime": 1621022700,
      "yearHigh": "191.89",
      "dayHigh": "171.69",
      "volume": 26753.0,
      "yearLow": "158.01",
      "dayLow": "170.62",
      "pctChange": "-0.28"
    },
    "BOVA11:BZ": {
      "securityType": "ETP",
      "symbol": "BOVA11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ETP",
      "region": "AMERICAS",
      "ticker": "bova11:bz",
      "tickerName": "BOVA11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "iShares Ibovespa",
      "name": "iShares Ibovespa",
      "watchlist": true,
      "resourceId": "BOVA11:BZ",
      "last": "117.24",
      "netChange": "1.20",
      "lastPriceTime": 1621023443,
      "yearHigh": "120.66",
      "dayHigh": "117.56",
      "volume": 5048994.0,
      "yearLow": "74.48",
      "dayLow": "116.38",
      "pctChange": "1.03"
    },
    "AAPL:US": {
      "securityType": "Common Stock",
      "symbol": "AAPL",
      "exchange": "NASDAQ GS",
      "country": "United States",
      "currency": "USD",
      "resourceType": "Company",
      "fundamentalDataCurrency": "USD",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "aapl:us",
      "tickerName": "AAPL:US",
      "template": "Stock",
      "tinyName": "Apple Inc",
      "name": "Apple Inc",
      "watchlist": true,
      "resourceId": "AAPL:US",
      "last": "127.45",
      "netChange": "2.48",
      "lastPriceTime": 1621036800,
      "pctChange1M": "-5.24",
      "yearHigh": "145.09",
      "dayHigh": "127.89",
      "volume": 81917951,
      "yearLow": "75.05",
      "dayLow": "125.85",
      "pctChangeYTD": "-3.95",
      "pctChange": "1.98"
    }
  }
};
