const kSearchResponseMap = {
  "quote": [
    {
      "securityType": "Common Stock",
      "symbol": "PSSA3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "pssa3:bz",
      "tickerName": "PSSA3:BZ",
      "template": "Stock",
      "tinyName": "Porto Seguro SA",
      "name": "Porto Seguro SA",
      "watchlist": true,
      "resourceId": "PSSA3:BZ",
      "id": "PSSA3:BZ",
      "title": "Porto Seguro SA",
      "card": "security"
    },
    {
      "securityType": "Common Stock",
      "symbol": "ITUB3",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Company",
      "fundamentalDataCurrency": "BRL",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "itub3:bz",
      "tickerName": "ITUB3:BZ",
      "template": "Stock",
      "tinyName": "Itaú Unibanco",
      "name": "Itaú Unibanco",
      "watchlist": true,
      "resourceId": "ItUB:BZ",
      "id": "PSSA3:BZ",
      "title": "Itaú Unibanco",
      "card": "security"
    },
    {
      "securityType": "Closed-End Fund",
      "symbol": "XPML11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ClosedEnd",
      "region": "AMERICAS",
      "ticker": "xpml11:bz",
      "tickerName": "XPML11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "XP MALLS FDO INV IMOB FII",
      "name": "XP MALLS FDO INV IMOB FII",
      "watchlist": true,
      "resourceId": "XPML11:BZ",
      "id": "XPML11:BZ",
      "title": "XP MALLS FDO INV IMOB FII",
      "card": "security"
    },
    {
      "securityType": "Closed-End Fund",
      "symbol": "HGLG11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ClosedEnd",
      "region": "AMERICAS",
      "ticker": "hglg11:bz",
      "tickerName": "HGLG11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "CSHG LOGÍSTICA FDO INV IMOB - FII",
      "name": "CSHG LOGÍSTICA FDO INV IMOB - FII",
      "watchlist": true,
      "resourceId": "HGLG11:BZ",
      "id": "HGLG11:BZ",
      "title": "CSHG LOGÍSTICA FDO INV IMOB - FII",
      "card": "security"
    },
    {
      "securityType": "ETP",
      "symbol": "BOVA11",
      "exchange": "B3 Day",
      "country": "Brazil",
      "currency": "BRL",
      "resourceType": "Fund",
      "resourceSubtype": "ETP",
      "region": "AMERICAS",
      "ticker": "bova11:bz",
      "tickerName": "BOVA11:BZ",
      "template": "Closed-End Fund",
      "tinyName": "iShares Ibovespa",
      "name": "iShares Ibovespa",
      "watchlist": true,
      "resourceId": "BOVA11:BZ",
      "id": "BOVA11:BZ",
      "title": "iShares Ibovespa",
      "card": "security"
    },
    {
      "securityType": "Common Stock",
      "symbol": "AAPL",
      "exchange": "NASDAQ GS",
      "country": "United States",
      "currency": "USD",
      "resourceType": "Company",
      "fundamentalDataCurrency": "USD",
      "resourceSubtype": "Public",
      "region": "AMERICAS",
      "ticker": "aapl:us",
      "tickerName": "AAPL:US",
      "template": "Stock",
      "tinyName": "Apple Inc",
      "name": "Apple Inc",
      "watchlist": true,
      "resourceId": "AAPL:US",
      "id": "AAPL:US",
      "title": "Apple Inc",
      "card": "security"
    },
  ],
  "news": []
};
